name: 'Build and Push Docker Image versioned by package.json and build-info.json'
description: 'Builds and pushes a Docker image to a Docker registry'
inputs:
  username:
    description: 'Username per il Docker registry'
    required: true
  password:
    description: 'Password per il Docker registry'
    required: true
  path:
    description: 'Percorso alla directory di contesto per Docker'
    required: false
    default: '.'
  registry:
    description: 'Registry Docker'
    required: true
  npm_token:
    description: 'Token Npm per private registry'
    required: false
  owner:
    description: 'Proprietario del repository'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.cjs'
boxbranding:
  color: "red"
  icon: "box"